# golangci-lint configuration v2

version: "2"

run:
  timeout: 5m

linters:
  enable:
    - staticcheck
    - govet
    - errcheck
    - gosec
    - misspell
    - revive
  settings:
    gosec:
      excludes:
        - G304
        - G306

  exclusions:
    rules:
      - path: _test\.go
        linters:
          - errcheck
