// Package output handles writing Relicta configuration files.
package output

import (
	"os"

	"gopkg.in/yaml.v3"

	"github.com/relicta-tech/migrate/internal/converter"
)

// ToYAML converts a RelictaConfig to YAML string.
func ToYAML(config *converter.RelictaConfig) (string, error) {
	data, err := yaml.Marshal(config)
	if err != nil {
		return "", err
	}

	// Add header comment
	header := `# Relicta Release Configuration
# Generated by relicta-migrate
# Documentation: https://github.com/relicta-tech/relicta

`
	return header + string(data), nil
}

// WriteYAML writes a RelictaConfig to a YAML file.
func WriteYAML(path string, config *converter.RelictaConfig) error {
	content, err := ToYAML(config)
	if err != nil {
		return err
	}

	return os.WriteFile(path, []byte(content), 0644)
}
